[package]
name = "opencc-clip-jieba"
version = "0.7.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencc-jieba-rs = {path = "../.."}
copypasta = "0.10.2"
clap = "4.5.57"
